# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单总数')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='完成订单数')),
                ('cancelled_orders', models.IntegerField(default=0, verbose_name='取消订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总营收')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款金额')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='净收入')),
                ('new_customers', models.IntegerField(default=0, verbose_name='新增客户数')),
                ('total_customers', models.IntegerField(default=0, verbose_name='客户总数')),
                ('active_employees', models.IntegerField(default=0, verbose_name='活跃陪玩师数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总服务时长(分钟)')),
                ('avg_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客单价')),
            ],
            options={
                'verbose_name': '日统计',
                'verbose_name_plural': '日统计',
                'db_table': 'stat_daily',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(verbose_name='日期')),
                ('period', models.CharField(choices=[('daily', '日'), ('weekly', '周'), ('monthly', '月')], default='daily', max_length=20, verbose_name='周期')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总时长(分钟)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='平均评分')),
                ('rank', models.IntegerField(default=0, verbose_name='排名')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '陪玩师排行',
                'verbose_name_plural': '陪玩师排行',
                'db_table': 'stat_employee_rank',
                'ordering': ['-date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单总数')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='完成订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总营收')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款金额')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='净收入')),
                ('new_customers', models.IntegerField(default=0, verbose_name='新增客户数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总服务时长(分钟)')),
            ],
            options={
                'verbose_name': '月统计',
                'verbose_name_plural': '月统计',
                'db_table': 'stat_monthly',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
