# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('settlement_no', models.CharField(max_length=50, unique=True, verbose_name='结算单号')),
                ('type', models.CharField(choices=[('daily', '日结'), ('weekly', '周结'), ('monthly', '月结'), ('manual', '手动结算')], default='daily', max_length=20, verbose_name='结算类型')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('processing', '结算中'), ('completed', '已结算'), ('failed', '结算失败')], default='pending', max_length=20, verbose_name='结算状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='结算总额')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总提成')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总利润')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '结算单',
                'verbose_name_plural': '结算单',
                'db_table': 'fin_settlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总时长(分钟)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总额')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='提成金额')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='提成比例(%)')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('completed', '已结算')], default='pending', max_length=20, verbose_name='状态')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_details', to='employee.employee', verbose_name='陪玩师')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.settlement', verbose_name='结算单')),
            ],
            options={
                'verbose_name': '结算明细',
                'verbose_name_plural': '结算明细',
                'db_table': 'fin_settlement_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='余额')),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='冻结金额')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计收入')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计支出')),
                ('type', models.CharField(choices=[('platform', '平台账户'), ('user', '用户账户'), ('employee', '陪玩师账户')], default='platform', max_length=20, verbose_name='账户类型')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包',
                'verbose_name_plural': '钱包',
                'db_table': 'fin_wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='关联订单号')),
                ('transaction_no', models.CharField(max_length=50, unique=True, verbose_name='流水号')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出'), ('freeze', '冻结'), ('unfreeze', '解冻'), ('transfer', '转账')], max_length=20, verbose_name='流水类型')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='交易后余额')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='employee.employee', verbose_name='陪玩师')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet', verbose_name='钱包')),
            ],
            options={
                'verbose_name': '财务流水',
                'verbose_name_plural': '财务流水',
                'db_table': 'fin_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('withdraw_no', models.CharField(max_length=50, unique=True, verbose_name='提现单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际到账金额')),
                ('withdraw_method', models.CharField(choices=[('bank', '银行卡'), ('alipay', '支付宝'), ('wechat', '微信')], default='bank', max_length=20, verbose_name='提现方式')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='账户名称')),
                ('account_no', models.CharField(blank=True, max_length=100, verbose_name='账号')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('audit_remark', models.CharField(blank=True, max_length=500, verbose_name='审核备注')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'db_table': 'fin_withdraw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('salary_no', models.CharField(max_length=50, unique=True, verbose_name='工资单号')),
                ('month', models.CharField(max_length=7, verbose_name='月份(YYYY-MM)')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='底薪')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='提成')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='奖金')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='扣款')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发工资')),
                ('status', models.CharField(choices=[('pending', '待发放'), ('processing', '发放中'), ('paid', '已发放'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('pay_method', models.CharField(choices=[('bank', '银行卡'), ('alipay', '支付宝'), ('wechat', '微信'), ('cash', '现金')], default='bank', max_length=20, verbose_name='发放方式')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employee.employee', verbose_name='陪玩师')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '工资单',
                'verbose_name_plural': '工资单',
                'db_table': 'fin_salary',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
