# Generated by Django 4.2.30 on 2026-08-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_add_work_status_attendance'),
        ('customer', '0007_customer_coins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='settlementdetail',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_details', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('recharge_no', models.CharField(max_length=50, unique=True, verbose_name='充值单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额')),
                ('coins', models.IntegerField(verbose_name='充值黑钻数量')),
                ('ratio', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='兑换比例(1元=多少黑钻)')),
                ('payment_method', models.CharField(choices=[('balance', '余额充值'), ('alipay', '支付宝'), ('wechat', '微信'), ('bank', '银行卡')], default='balance', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='completed', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='customer.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharges', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'fin_recharge',
                'ordering': ['-created_at'],
            },
        ),
    ]
