# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, verbose_name='配置值')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='配置名称')),
                ('type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON'), ('text', '文本')], default='string', max_length=20, verbose_name='类型')),
                ('group', models.CharField(default='basic', max_length=50, verbose_name='分组')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'sys_config',
                'ordering': ['group', 'sort', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='字典编码')),
                ('type', models.CharField(choices=[('list', '列表'), ('tree', '树形')], default='list', max_length=20, verbose_name='类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
                'db_table': 'sys_dictionary',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type', models.CharField(max_length=100, verbose_name='错误类型')),
                ('message', models.TextField(verbose_name='错误信息')),
                ('traceback', models.TextField(blank=True, verbose_name='堆栈信息')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('params', models.TextField(blank=True, verbose_name='请求参数')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错误日志',
                'verbose_name_plural': '错误日志',
                'db_table': 'sys_error_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='模块')),
                ('operation', models.CharField(blank=True, max_length=100, verbose_name='操作')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('params', models.TextField(blank=True, verbose_name='请求参数')),
                ('result', models.TextField(blank=True, verbose_name='返回结果')),
                ('status_code', models.IntegerField(default=200, verbose_name='状态码')),
                ('duration', models.FloatField(default=0, verbose_name='耗时(秒)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='样式类')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system.dictionary', verbose_name='字典')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='system.dictionaryitem', verbose_name='上级')),
            ],
            options={
                'verbose_name': '字典项',
                'verbose_name_plural': '字典项',
                'db_table': 'sys_dictionary_item',
                'ordering': ['sort', 'id'],
                'unique_together': {('dictionary', 'value')},
            },
        ),
    ]
