# Generated by Django 4.2.30 on 2026-07-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSKeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('keyword', models.CharField(help_text='触发自动回复的关键词', max_length=200, verbose_name='关键词')),
                ('reply_text', models.TextField(help_text='匹配关键词后自动回复的内容', verbose_name='回复内容')),
                ('match_type', models.CharField(choices=[('contains', '包含'), ('exact', '完全匹配'), ('startswith', '开头匹配')], default='contains', max_length=20, verbose_name='匹配方式')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '客服关键词规则',
                'verbose_name_plural': '客服关键词规则',
                'db_table': 'sys_cs_keyword_rule',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CSWelcomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('welcome_text', models.TextField(help_text='客户进入客服聊天时自动发送的欢迎语', verbose_name='欢迎语内容')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '客服欢迎语配置',
                'verbose_name_plural': '客服欢迎语配置',
                'db_table': 'sys_cs_welcome_config',
            },
        ),
    ]
