# Generated by Django 4.1.13 on 2026-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20260725_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cskeywordrule',
            name='keyword',
            field=models.CharField(help_text='触发自动回复的关键词', max_length=200, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='cskeywordrule',
            name='reply_text',
            field=models.TextField(help_text='匹配关键词后自动回复的内容', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='cswelcomeconfig',
            name='welcome_text',
            field=models.TextField(blank=True, default='', help_text='客户进入客服聊天时自动发送的欢迎语', verbose_name='欢迎语内容'),
        ),
    ]
