# Generated by Django 4.2.30 on 2026-08-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_add_ban_freeze'),
        ('system', '0003_alter_cskeywordrule_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(help_text='如"七折券"', max_length=100, verbose_name='券名')),
                ('coupon_type', models.CharField(choices=[('discount', '减免券')], default='discount', max_length=20, verbose_name='券类型')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=70.0, help_text='如70表示打七折，实际支付金额 × 70%', max_digits=5, verbose_name='折扣比例(%)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='满多少元可用，0表示不限', max_digits=10, verbose_name='最低订单金额')),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='单次最多优惠多少元，0表示不限', max_digits=10, verbose_name='最大优惠金额(元)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='使用说明')),
            ],
            options={
                'verbose_name': '优惠券模板',
                'verbose_name_plural': '优惠券模板',
                'db_table': 'sys_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('used_order_no', models.CharField(blank=True, max_length=50, verbose_name='使用订单号')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='system.coupon', verbose_name='券模板')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='customer.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_coupons', to=settings.AUTH_USER_MODEL, verbose_name='发放人')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'sys_user_coupon',
                'ordering': ['-created_at'],
            },
        ),
    ]
