# Generated by Django 4.2.30 on 2026-08-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_add_coupon_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deduction_coins',
            field=models.IntegerField(default=0, help_text='抵扣券专用：直接抵扣的黑钻数量，如500表示抵扣500黑钻', verbose_name='抵扣黑钻数'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('discount', '减免券'), ('deduction', '抵扣券')], default='discount', max_length=20, verbose_name='券类型'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='减免券专用：如70表示打七折，实际支付金额 × 70%', max_digits=5, verbose_name='折扣比例(%)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(help_text='如"七折券"或"500黑钻券"', max_length=100, verbose_name='券名'),
        ),
    ]
