# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('notice', '通知'), ('marketing', '营销'), ('code', '验证码')], default='notice', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_msg', models.CharField(blank=True, max_length=500, verbose_name='错误信息')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件发送记录',
                'verbose_name_plural': '邮件发送记录',
                'db_table': 'notice_email_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('code', '验证码'), ('notice', '通知'), ('marketing', '营销')], default='code', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_msg', models.CharField(blank=True, max_length=500, verbose_name='错误信息')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '短信发送记录',
                'verbose_name_plural': '短信发送记录',
                'db_table': 'notice_sms_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('order', '订单通知'), ('finance', '财务通知'), ('activity', '活动通知'), ('other', '其他')], default='system', max_length=20, verbose_name='通知类型')),
                ('level', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('danger', '重要'), ('success', '成功')], default='normal', max_length=20, verbose_name='级别')),
                ('target_type', models.CharField(choices=[('all', '全部用户'), ('role', '指定角色'), ('employee', '指定陪玩师'), ('user', '指定用户')], default='all', max_length=20, verbose_name='目标类型')),
                ('target_ids', models.TextField(blank=True, verbose_name='目标ID列表')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('jump_url', models.CharField(blank=True, max_length=500, verbose_name='跳转链接')),
                ('extra', models.TextField(blank=True, verbose_name='附加数据')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notices', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notice_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='employee.employee', verbose_name='陪玩师')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_notices', to='notice.notice', verbose_name='通知')),
            ],
            options={
                'verbose_name': '陪玩师通知',
                'verbose_name_plural': '陪玩师通知',
                'db_table': 'notice_employee_notice',
                'ordering': ['-created_at'],
                'unique_together': {('notice', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notices', to='notice.notice', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'db_table': 'notice_user_notice',
                'ordering': ['-created_at'],
                'unique_together': {('notice', 'user')},
            },
        ),
    ]
