# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('md5', models.CharField(blank=True, max_length=32, verbose_name='MD5值')),
                ('category', models.CharField(choices=[('avatar', '头像'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('document', '文档'), ('contract', '合同'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('storage_type', models.CharField(choices=[('local', '本地存储'), ('oss', '阿里云OSS'), ('cos', '腾讯云COS'), ('minio', 'MinIO')], default='local', max_length=20, verbose_name='存储方式')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='访问URL')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽度(像素)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度(像素)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'upload_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
