# Generated by Django 4.2.30 on 2026-08-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('image', models.CharField(max_length=500, verbose_name='图片URL')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='跳转链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='wx.gamecategory', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏轮播图',
                'verbose_name_plural': '游戏轮播图',
                'db_table': 'wx_game_banner',
                'ordering': ['game__id', 'sort', '-created_at'],
            },
        ),
    ]
