# Generated by Django 4.1.13 on 2026-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_follow_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
