# Generated by Django 4.1.13 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_alter_follow_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='banner',
            field=models.CharField(blank=True, max_length=500, verbose_name='横幅URL'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='分类介绍'),
        ),
    ]
