# Generated by Django 4.2.30 on 2026-08-09 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wx', '0005_gamecategory_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('game_account', models.CharField(max_length=200, verbose_name='游戏账号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to='wx.gamecategory', verbose_name='游戏品类')),
            ],
            options={
                'verbose_name': '游戏账号',
                'verbose_name_plural': '游戏账号',
                'db_table': 'wx_game_account',
                'ordering': ['id'],
                'unique_together': {('user', 'game_category')},
            },
        ),
    ]
