# Generated by Django 4.2.30 on 2026-08-09 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wx', '0006_add_game_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DasherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_card_front', models.CharField(max_length=500, verbose_name='身份证正面')),
                ('id_card_back', models.CharField(max_length=500, verbose_name='身份证反面')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('agree_terms', models.BooleanField(default=True, verbose_name='同意协议')),
                ('review_remark', models.CharField(blank=True, max_length=500, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dasher_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '入驻申请',
                'verbose_name_plural': '入驻申请',
                'db_table': 'wx_dasher_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
