# Generated by Django 4.2.30 on 2026-08-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wx', '0007_add_dasher_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('selections', models.JSONField(default=dict, verbose_name='下单选项')),
                ('status', models.CharField(choices=[('pending', '待下单'), ('used', '已下单'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('cs_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_preorders', to=settings.AUTH_USER_MODEL, verbose_name='客服')),
            ],
            options={
                'verbose_name': '预下单',
                'verbose_name_plural': '预下单',
                'db_table': 'wx_pre_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
