# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班次名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('type', models.CharField(choices=[('morning', '早班'), ('noon', '午班'), ('evening', '晚班'), ('night', '夜班'), ('normal', '正常班'), ('custom', '自定义')], default='normal', max_length=20, verbose_name='班次类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '班次',
                'db_table': 'sch_shift',
                'ordering': ['sort', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(分钟)')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('timeout', '已超时')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customer.customer', verbose_name='客户')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='employee.employee', verbose_name='陪玩师')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='employee.employeeskill', verbose_name='技能')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'sch_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('leave_type', models.CharField(choices=[('personal', '事假'), ('sick', '病假'), ('annual', '年假'), ('marriage', '婚假'), ('maternity', '产假'), ('other', '其他')], default='personal', max_length=20, verbose_name='请假类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='时长(天)')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approve_remark', models.CharField(blank=True, max_length=500, verbose_name='审核备注')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '请假',
                'verbose_name_plural': '请假',
                'db_table': 'sch_leave',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(verbose_name='日期')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('work_duration', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='工作时长(小时)')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early', '早退'), ('absent', '旷工'), ('leave', '请假'), ('rest', '休息')], default='normal', max_length=20, verbose_name='考勤状态')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='迟到分钟数')),
                ('early_minutes', models.IntegerField(default=0, verbose_name='早退分钟数')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('check_in_ip', models.CharField(blank=True, max_length=50, verbose_name='签到IP')),
                ('check_out_ip', models.CharField(blank=True, max_length=50, verbose_name='签退IP')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '考勤',
                'verbose_name_plural': '考勤',
                'db_table': 'sch_attendance',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('type', models.CharField(choices=[('work', '上班'), ('rest', '休息'), ('leave', '请假'), ('business', '出差'), ('overtime', '加班')], default='work', max_length=20, verbose_name='排班类型')),
                ('status', models.CharField(choices=[('scheduled', '已排班'), ('checked_in', '已签到'), ('checked_out', '已签退'), ('absent', '旷工'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employee.employee', verbose_name='陪玩师')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedule.shift', verbose_name='班次')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'db_table': 'sch_schedule',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
