# Generated by Django 4.2.30 on 2026-07-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_team_teammember'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('day_of_week', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_schedules', to='employee.employee', verbose_name='客服人员')),
            ],
            options={
                'verbose_name': '客服排班',
                'verbose_name_plural': '客服排班',
                'db_table': 'sch_cs_schedule',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
