# Generated by Django 4.2.30 on 2026-07-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed',
            field=models.BooleanField(default=False, verbose_name='客户已确认'),
        ),
        migrations.AddField(
            model_name='order',
            name='dasher_confirmed',
            field=models.BooleanField(default=False, verbose_name='打手已确认'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('published', '可领取'), ('claimed', '待开始'), ('confirming', '待双方确认'), ('in_progress', '进行中'), ('completed', '已结束'), ('reviewed', '已评价'), ('cancelled', '已取消')], default='published', max_length=20, verbose_name='订单状态'),
        ),
    ]
