# Generated by Django 4.2.30 on 2026-07-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_customer_confirmed_order_dasher_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='订单标题'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('single', '单人单'), ('multi', '多人单'), ('package', '套餐单'), ('self_service', '自助单')], default='single', max_length=20, verbose_name='订单类型'),
        ),
    ]
