# Generated by Django 4.2.30 on 2026-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_title_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locked_slots',
            field=models.IntegerField(default=0, verbose_name='已锁定席位'),
        ),
    ]
