# Generated by Django 4.2.30 on 2026-07-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_locked_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='免单原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='转单原因'),
        ),
    ]
