# Generated by Django 4.2.30 on 2026-07-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_team_teammember'),
        ('order', '0005_order_discount_reason_order_transfer_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_orders', to='employee.employee', verbose_name='队长'),
        ),
    ]
