# Generated by Django 4.2.30 on 2026-07-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_gender'),
        ('order', '0012_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='employee.employee', verbose_name='预约打手'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='ordermember',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_members', to='employee.employee', verbose_name='陪玩师'),
        ),
    ]
