# Generated by Django 4.2.30 on 2026-07-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0013_alter_employee_gender'),
        ('customer', '0005_add_order_candidate'),
        ('order', '0013_order_assigned_employee_alter_ordercomment_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': '售后工单', 'verbose_name_plural': '售后工单'},
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='employee.employee', verbose_name='预约打手'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='order.ordermember', verbose_name='订单成员'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='order.order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='ordermember',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_members', to='employee.employee', verbose_name='陪玩师'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='customer.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True, verbose_name='工单描述'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='employee.employee', verbose_name='打手'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='handle_remark',
            field=models.TextField(blank=True, verbose_name='处理备注'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='order.order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='order_snapshot',
            field=models.JSONField(default=dict, verbose_name='订单快照'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='工单号'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='工单标题'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='OrderCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_candidates', to='employee.employee', verbose_name='陪玩师')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '选秀候选人',
                'verbose_name_plural': '选秀候选人',
                'db_table': 'ord_order_candidate',
                'ordering': ['created_at'],
                'unique_together': {('order', 'employee')},
            },
        ),
    ]
