# Generated by Django 4.1.13 on 2026-08-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_cleanup_old_order_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='self_service_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='自助下单快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_unit',
            field=models.CharField(blank=True, choices=[('round', '局'), ('hour', '小时')], max_length=20, verbose_name='结算单位'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('published', '可领取'), ('transferring', '转单中'), ('claimed', '待开始'), ('confirming', '待双方确认'), ('in_progress', '进行中'), ('completed', '已结束'), ('reviewed', '已评价'), ('cancelled', '已取消')], default='published', max_length=20, verbose_name='订单状态'),
        ),
    ]
