# Generated by Django 4.2.30 on 2026-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_ordercandidate_trial_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠券折扣金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('published', '可领取'), ('transferring', '转单中'), ('claimed', '待开始'), ('confirming', '待客户确认'), ('in_progress', '进行中'), ('completed', '已结束'), ('reviewed', '已评价'), ('cancelled', '已取消')], default='published', max_length=20, verbose_name='订单状态'),
        ),
    ]
