# Generated by Django 4.2.30 on 2026-08-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_add_ban_freeze'),
        ('order', '0019_add_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='转单费(元)'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_out_orders', to='employee.employee', verbose_name='转出打手'),
        ),
    ]
