# Generated by Django 4.2.30 on 2026-08-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_add_transfer_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_images',
            field=models.TextField(blank=True, verbose_name='完成凭证图片(逗号分隔URL)'),
        ),
    ]
