# Generated by Django 4.2.30 on 2026-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信openid'),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_unionid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信unionid'),
        ),
    ]
