# Generated by Django 4.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_add_wx_openid'),
        ('account', '0002_user_avatar_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像'),
        ),
    ]
