# Generated by Django 4.2.30 on 2026-08-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_avatar_alter_user_wx_openid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='黑金ID'),
        ),
    ]
