# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技能名称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('icon', models.ImageField(blank=True, upload_to='skills/', verbose_name='图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '陪玩技能',
                'verbose_name_plural': '陪玩技能',
                'db_table': 'emp_skill',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='标签颜色')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '陪玩师标签',
                'verbose_name_plural': '陪玩师标签',
                'db_table': 'emp_tag',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='艺名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('avatar', models.ImageField(blank=True, upload_to='employees/avatars/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('id_card', models.CharField(blank=True, max_length=30, verbose_name='身份证号')),
                ('id_card_verified', models.BooleanField(default=False, verbose_name='实名认证')),
                ('level', models.CharField(choices=[('new', '新人'), ('normal', '普通'), ('silver', '白银'), ('gold', '黄金'), ('diamond', '钻石'), ('king', '王者')], default='normal', max_length=20, verbose_name='等级')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('busy', '接单中'), ('offline', '离线'), ('rest', '休息'), ('leave', '请假')], default='idle', max_length=20, verbose_name='接单状态')),
                ('online_status', models.BooleanField(default=False, verbose_name='在线状态')),
                ('intro', models.TextField(blank=True, verbose_name='个人简介')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分')),
                ('order_count', models.IntegerField(default=0, verbose_name='接单总数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总时长(分钟)')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户行')),
                ('bank_card', models.CharField(blank=True, max_length=50, verbose_name='银行卡号')),
                ('alipay', models.CharField(blank=True, max_length=100, verbose_name='支付宝')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ号')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='account.department', verbose_name='所属部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '陪玩师',
                'verbose_name_plural': '陪玩师',
                'db_table': 'emp_employee',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('contract_type', models.CharField(choices=[('employment', '劳动合同'), ('cooperation', '合作协议'), ('parttime', '兼职协议')], default='employment', max_length=20, verbose_name='合同类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已到期'), ('terminated', '已终止')], default='active', max_length=20, verbose_name='合同状态')),
                ('file', models.FileField(blank=True, upload_to='contracts/', verbose_name='合同文件')),
                ('salary_type', models.CharField(choices=[('fixed', '固定工资'), ('commission', '提成'), ('mix', '底薪+提成')], default='commission', max_length=20, verbose_name='薪资类型')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='底薪')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='提成比例(%)')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '陪玩师合同',
                'verbose_name_plural': '陪玩师合同',
                'db_table': 'emp_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '熟练'), ('skilled', '精通'), ('master', '大师')], default='skilled', max_length=20, verbose_name='熟练度')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/小时)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='employee.employee', verbose_name='陪玩师')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_relations', to='employee.employeeskill', verbose_name='技能')),
            ],
            options={
                'verbose_name': '陪玩师技能关系',
                'verbose_name_plural': '陪玩师技能关系',
                'db_table': 'emp_skill_relation',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(related_name='employees', through='employee.EmployeeSkillRelation', to='employee.employeeskill', verbose_name='技能'),
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('last_order_time', models.DateTimeField(blank=True, null=True, verbose_name='最后接单时间')),
                ('today_orders', models.IntegerField(default=0, verbose_name='今日订单数')),
                ('today_duration', models.IntegerField(default=0, verbose_name='今日时长(分钟)')),
                ('today_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='今日收入')),
                ('device', models.CharField(blank=True, max_length=50, verbose_name='设备信息')),
                ('login_ip', models.CharField(blank=True, max_length=50, verbose_name='登录IP')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_detail', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '陪玩师状态',
                'verbose_name_plural': '陪玩师状态',
                'db_table': 'emp_status',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employee.employeetag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='EmployeeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='余额')),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='冻结金额')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计收入')),
                ('total_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计提现')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='employee.employee', verbose_name='陪玩师')),
            ],
            options={
                'verbose_name': '陪玩师钱包',
                'verbose_name_plural': '陪玩师钱包',
                'db_table': 'emp_wallet',
            },
        ),
    ]
