# Generated by Django 4.2.30 on 2026-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_add_game_category_to_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level_num',
            field=models.IntegerField(default=0, verbose_name='等级数值'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('idle', '空闲中'), ('busy', '接单中'), ('offline', '离线'), ('rest', '休息'), ('leave', '请假')], default='idle', max_length=20, verbose_name='接单状态'),
        ),
    ]
