# Generated by Django 4.2.30 on 2026-07-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_level_num_alter_employee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['sort', '-created_at'], 'verbose_name': '打手', 'verbose_name_plural': '打手'},
        ),
        migrations.AlterModelOptions(
            name='employeecontract',
            options={'ordering': ['-created_at'], 'verbose_name': '打手合同', 'verbose_name_plural': '打手合同'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'ordering': ['sort', 'id'], 'verbose_name': '打手技能', 'verbose_name_plural': '打手技能'},
        ),
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'verbose_name': '打手状态', 'verbose_name_plural': '打手状态'},
        ),
        migrations.AlterModelOptions(
            name='employeetag',
            options={'ordering': ['sort', 'id'], 'verbose_name': '打手标签', 'verbose_name_plural': '打手标签'},
        ),
        migrations.AlterModelOptions(
            name='employeewallet',
            options={'verbose_name': '打手钱包', 'verbose_name_plural': '打手钱包'},
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employee.employee', verbose_name='打手'),
        ),
        migrations.AlterField(
            model_name='employeeskillrelation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='employee.employee', verbose_name='打手'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_detail', to='employee.employee', verbose_name='打手'),
        ),
        migrations.AlterField(
            model_name='employeewallet',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='employee.employee', verbose_name='打手'),
        ),
    ]
