# Generated by Django 4.2.30 on 2026-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='price_max_beginner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='入门最高时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_max_intermediate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='熟练最高时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_max_master',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='大师最高时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_max_skilled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='精通最高时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_min_beginner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='入门最低时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_min_intermediate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='熟练最低时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_min_master',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='大师最低时薪'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='price_min_skilled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='精通最低时薪'),
        ),
    ]
