# Generated by Django 4.2.30 on 2026-07-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeskill_price_max_beginner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_max_beginner',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_max_intermediate',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_max_master',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_max_skilled',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_min_beginner',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_min_intermediate',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_min_master',
        ),
        migrations.RemoveField(
            model_name='employeeskill',
            name='price_min_skilled',
        ),
        migrations.RemoveField(
            model_name='employeeskillrelation',
            name='level',
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='段位名称')),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低时薪')),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最高时薪')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='employee.employeeskill', verbose_name='所属技能')),
            ],
            options={
                'verbose_name': '技能段位',
                'verbose_name_plural': '技能段位',
                'db_table': 'emp_skill_level',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employeeskillrelation',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_relations', to='employee.skilllevel', verbose_name='段位'),
        ),
    ]
