# Generated by Django 4.2.30 on 2026-07-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employeeskill_price_max_beginner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='提成比例(%)'),
        ),
    ]
