# Generated by Django 4.2.30 on 2026-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='佣金余额(可提现)'),
        ),
    ]
