# Generated by Django 4.2.30 on 2026-07-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='队伍名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('max_members', models.IntegerField(default=5, verbose_name='最大人数')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='employee.employee', verbose_name='队长')),
            ],
            options={
                'verbose_name': '打手组队',
                'verbose_name_plural': '打手组队',
                'db_table': 'emp_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('active', '正常'), ('invited', '已邀请待确认'), ('left', '已退出')], default='active', max_length=20, verbose_name='状态')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='employee.employee', verbose_name='打手')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='employee.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '组队成员',
                'verbose_name_plural': '组队成员',
                'db_table': 'emp_team_member',
                'unique_together': {('team', 'employee')},
            },
        ),
    ]
