# Generated by Django 4.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价(元/小时)'),
        ),
    ]
