# Generated by Django 4.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeeskill_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='时薪(元/小时)'),
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='price_max',
        ),
    ]
