# Generated by Django 4.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_skilllevel_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像'),
        ),
    ]
