# Generated by Django 4.2.30 on 2026-07-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='skill_type',
            field=models.CharField(choices=[('primary', '主技能'), ('secondary', '副技能')], default='secondary', max_length=20, verbose_name='技能类型'),
        ),
        migrations.AddField(
            model_name='employeeskillrelation',
            name='skill_type',
            field=models.CharField(choices=[('primary', '主技能'), ('secondary', '副技能')], default='secondary', max_length=20, verbose_name='技能类型'),
        ),
    ]
