# Generated by Django 4.1.13 on 2026-08-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_add_work_status_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='description',
            field=models.TextField(blank=True, verbose_name='技能介绍'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='order_notice',
            field=models.TextField(blank=True, verbose_name='下单须知'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='remark_placeholder',
            field=models.CharField(blank=True, default='选填，不超过30个字', max_length=200, verbose_name='备注提示'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='self_service_enabled',
            field=models.BooleanField(default=False, verbose_name='启用自助下单'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='trial_mode',
            field=models.CharField(choices=[('disabled', '不支持试音'), ('optional', '可选试音'), ('required', '必须试音')], default='optional', max_length=20, verbose_name='试音模式'),
        ),
        migrations.CreateModel(
            name='SkillGameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='玩法名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='玩法说明')),
                ('difficulty_enabled', models.BooleanField(default=False, verbose_name='启用难度')),
                ('gender_limit', models.CharField(choices=[('unlimited', '不限'), ('male', '只男'), ('female', '只女')], default='unlimited', max_length=20, verbose_name='服务者性别')),
                ('companion_mode', models.CharField(choices=[('single', '单陪'), ('double', '双陪'), ('both', '单陪和双陪')], default='single', max_length=20, verbose_name='陪玩类型')),
                ('settlement_unit', models.CharField(choices=[('round', '局'), ('hour', '小时')], default='hour', max_length=20, verbose_name='结算单位')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='最低购买量')),
                ('quantity_step', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='购买步长')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础单价')),
                ('remark_required', models.BooleanField(default=False, verbose_name='必须填写备注')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_service_gameplays', to='employee.employeeskill', verbose_name='所属技能')),
            ],
            options={
                'db_table': 'emp_skill_gameplay',
                'ordering': ['sort', 'id'],
                'unique_together': {('skill', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameplayService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=80, verbose_name='服务名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='服务说明')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加价')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='employee.skillgameplay', verbose_name='所属玩法')),
            ],
            options={
                'db_table': 'emp_gameplay_service',
                'ordering': ['sort', 'id'],
                'unique_together': {('gameplay', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameplayPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('difficulty_name', models.CharField(blank=True, max_length=50, verbose_name='难度')),
                ('level_name', models.CharField(blank=True, max_length=50, verbose_name='等级')),
                ('service_name', models.CharField(blank=True, max_length=80, verbose_name='服务')),
                ('companion_type', models.CharField(choices=[('single', '单陪'), ('double', '双陪')], default='single', max_length=20, verbose_name='陪玩类型')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='组合单价')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='employee.skillgameplay', verbose_name='所属玩法')),
            ],
            options={
                'db_table': 'emp_gameplay_price_rule',
                'ordering': ['id'],
                'unique_together': {('gameplay', 'difficulty_name', 'level_name', 'service_name', 'companion_type')},
            },
        ),
        migrations.CreateModel(
            name='GameplayLevelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='等级说明')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加价')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_options', to='employee.skillgameplay', verbose_name='所属玩法')),
            ],
            options={
                'db_table': 'emp_gameplay_level',
                'ordering': ['sort', 'id'],
                'unique_together': {('gameplay', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameplayDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='难度名称')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加价')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('gameplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='employee.skillgameplay', verbose_name='所属玩法')),
            ],
            options={
                'db_table': 'emp_gameplay_difficulty',
                'ordering': ['sort', 'id'],
                'unique_together': {('gameplay', 'name')},
            },
        ),
    ]
