# Generated by Django 4.2.30 on 2026-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employeeskill_description_employeeskill_order_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayleveloption',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
        migrations.AddField(
            model_name='gameplayservice',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
