# Generated by Django 4.2.30 on 2026-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_add_is_recommended_to_gameplay_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplaypricerule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameplayleveloption',
            name='allowed_services',
            field=models.JSONField(blank=True, default=list, verbose_name='允许的服务名称（空=全部）'),
        ),
        migrations.AddField(
            model_name='gameplaypricerule',
            name='gender_requirement',
            field=models.CharField(choices=[('any', '不限'), ('male', '男'), ('female', '女')], default='any', max_length=20, verbose_name='性别要求'),
        ),
        migrations.AddField(
            model_name='skillgameplay',
            name='female_price_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='选女加价'),
        ),
        migrations.AddField(
            model_name='skillgameplay',
            name='male_price_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='选男加价'),
        ),
        migrations.AlterField(
            model_name='skillgameplay',
            name='gender_limit',
            field=models.CharField(choices=[('unlimited', '不限（不加价）'), ('male_only', '只男（固定）'), ('female_only', '只女（固定）'), ('optional', '性别可选（加价）')], default='unlimited', max_length=20, verbose_name='服务者性别'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplaypricerule',
            unique_together={('gameplay', 'difficulty_name', 'level_name', 'service_name', 'gender_requirement', 'companion_type')},
        ),
    ]
