# Generated by Django 4.1.13 on 2026-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_servicevalueadded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueaddedservice',
            options={'ordering': ['sort', 'id'], 'verbose_name': '附加项目', 'verbose_name_plural': '附加项目'},
        ),
        migrations.AlterField(
            model_name='valueaddedservice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
