# Generated by Django 4.1.13 on 2026-08-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_valueaddedservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='voice_duration',
            field=models.IntegerField(default=0, verbose_name='语音时长(秒)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='voice_intro',
            field=models.FileField(blank=True, null=True, upload_to='employee_voice/%Y/%m/', verbose_name='语音介绍'),
        ),
    ]
