# Generated by Django 4.2.30 on 2026-08-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0004_alter_follow_is_deleted'),
        ('employee', '0025_alter_employee_voice_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='assignment_mode',
            field=models.CharField(choices=[('rank_auto', '达到段位自动拥有'), ('manual', '管理员手动添加')], default='manual', max_length=20, verbose_name='授予方式'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='pricing_unit',
            field=models.CharField(choices=[('hour', '每小时'), ('round', '每局')], default='hour', max_length=20, verbose_name='计价单位'),
        ),
        migrations.AddField(
            model_name='employeeskillrelation',
            name='assignment_source',
            field=models.CharField(choices=[('rank_auto', '段位自动授予'), ('manual', '管理员手动授予')], default='manual', max_length=20, verbose_name='授予来源'),
        ),
        migrations.AddField(
            model_name='employeeskillrelation',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='打手已开启'),
        ),
        migrations.AddField(
            model_name='employeeskillrelation',
            name='price_overridden',
            field=models.BooleanField(default=False, verbose_name='使用专属价格'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='icon',
            field=models.CharField(blank=True, max_length=500, verbose_name='图标URL'),
        ),
        migrations.CreateModel(
            name='GameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='段位名称')),
                ('sort', models.IntegerField(default=0, verbose_name='段位顺序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='wx.gamecategory', verbose_name='游戏分类')),
            ],
            options={
                'verbose_name': '游戏段位',
                'verbose_name_plural': '游戏段位',
                'db_table': 'emp_game_rank',
                'ordering': ['game_category_id', 'sort', 'id'],
                'unique_together': {('game_category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='required_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='employee.gamerank', verbose_name='所需段位'),
        ),
        migrations.CreateModel(
            name='EmployeeGameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rank_relations', to='employee.employee', verbose_name='打手')),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_rank_relations', to='wx.gamecategory', verbose_name='游戏分类')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_relations', to='employee.gamerank', verbose_name='当前段位')),
            ],
            options={
                'verbose_name': '打手游戏段位',
                'verbose_name_plural': '打手游戏段位',
                'db_table': 'emp_employee_game_rank',
                'unique_together': {('employee', 'game_category')},
            },
        ),
    ]
