# Generated by Django 4.2.30 on 2026-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_employee_assessment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='照片墙'),
        ),
    ]
