# Generated by Django 4.2.30 on 2026-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_add_photos_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_star',
            field=models.BooleanField(default=False, verbose_name='明星打手'),
        ),
        migrations.AddField(
            model_name='employee',
            name='star_sort',
            field=models.IntegerField(default=0, verbose_name='明星排序'),
        ),
    ]
