# Generated by Django 4.2.30 on 2026-08-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_employee_platform_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplaypresetitem',
            name='required_people',
            field=models.PositiveIntegerField(default=1, help_text='该预制单下单时锁定的人数，最低为1', verbose_name='所需人数'),
        ),
    ]
