# Generated by Django 4.2.30 on 2026-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_add_required_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_frozen',
            field=models.BooleanField(default=False, verbose_name='佣金是否冻结'),
        ),
    ]
