# Generated by Django 4.2.30 on 2026-08-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_add_ban_freeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='max_members',
            field=models.IntegerField(default=2, verbose_name='最大人数'),
        ),
    ]
