# Generated by Codex on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_team_max_members_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='quick_welcome_message',
            field=models.TextField(blank=True, default='', verbose_name='群聊快捷欢迎语'),
        ),
    ]
