# Generated by Django 4.2.30 on 2026-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_employee_quick_welcome_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgameplay',
            name='addon_section_desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='加购服务区块小字说明'),
        ),
        migrations.AddField(
            model_name='skillgameplay',
            name='more_service_section_desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='更多服务区块小字说明'),
        ),
        migrations.AddField(
            model_name='skillgameplay',
            name='service_section_desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='服务区块小字说明'),
        ),
    ]
