# Generated by Codex on 2026-08-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0040_add_gameplay_section_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=100, verbose_name='档案标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='档案分类')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '重要')], default='normal', max_length=20, verbose_name='重要级别')),
                ('content', models.TextField(verbose_name='档案内容')),
                ('next_follow_time', models.DateTimeField(blank=True, null=True, verbose_name='下次跟进时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to='employee.employee', verbose_name='打手')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_archive_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '打手档案记录',
                'verbose_name_plural': '打手档案记录',
                'db_table': 'emp_archive_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
