# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='等级名称')),
                ('level', models.IntegerField(unique=True, verbose_name='等级值')),
                ('icon', models.ImageField(blank=True, upload_to='customer_levels/', verbose_name='图标')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费金额')),
                ('discount', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='折扣比例(%)')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='等级颜色')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户等级',
                'verbose_name_plural': '客户等级',
                'db_table': 'cus_level',
                'ordering': ['level', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#1890ff', max_length=20, verbose_name='标签颜色')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '客户标签',
                'verbose_name_plural': '客户标签',
                'db_table': 'cus_tag',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, upload_to='customers/avatars/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信号')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计消费')),
                ('total_orders', models.IntegerField(default=0, verbose_name='累计订单数')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='账户余额')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源渠道')),
                ('first_order_date', models.DateTimeField(blank=True, null=True, verbose_name='首单时间')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='最后下单时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.customerlevel', verbose_name='客户等级')),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='customer.customertag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'cus_customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('reason', models.CharField(max_length=500, verbose_name='拉黑原因')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('status', models.BooleanField(default=True, verbose_name='是否生效')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_ops', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_records', to='customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
                'db_table': 'cus_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerConsumeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费金额')),
                ('type', models.CharField(choices=[('order', '订单消费'), ('recharge', '充值'), ('refund', '退款'), ('withdraw', '提现'), ('other', '其他')], default='order', max_length=20, verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consume_records', to='customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
                'db_table': 'cus_consume_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
