# Generated by Django 4.2.30 on 2026-07-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌')], default='online', max_length=20, verbose_name='在线状态')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cs_profile', to='customer.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '客服人员',
                'verbose_name_plural': '客服人员',
                'db_table': 'cus_service',
            },
        ),
        migrations.CreateModel(
            name='CSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('msg_type', models.CharField(choices=[('text', '文本'), ('image', '图片')], default='text', max_length=20, verbose_name='消息类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('sender_type', models.CharField(choices=[('customer', '客户'), ('cs', '客服')], default='customer', max_length=20, verbose_name='发送者类型')),
                ('cs_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='客服')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_messages', to='customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '客服消息',
                'verbose_name_plural': '客服消息',
                'db_table': 'cs_message',
                'ordering': ['created_at'],
            },
        ),
    ]
