# Generated by Django 4.2.30 on 2026-07-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_assigned_employee_alter_ordercomment_employee_and_more'),
        ('customer', '0002_customerservice_csmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmessage',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_messages', to='order.supportticket', verbose_name='关联工单'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像'),
        ),
    ]
