# Generated by Django 4.2.30 on 2026-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_csmessage_ticket_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('order_card', '订单卡片')], default='text', max_length=20, verbose_name='消息类型'),
        ),
    ]
