# Generated by Django 4.2.30 on 2026-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_add_work_status_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='黑钻数量'),
        ),
    ]
