# Generated by Django 4.2.30 on 2026-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_service_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coins_frozen',
            field=models.BooleanField(default=False, verbose_name='黑钻是否冻结'),
        ),
    ]
